WIP: Initial Agent.py creation
DonatasTamosauskas/dumbbells pull request #4
Opened 2021-04-01 13:21 UTC by Adriman32

…tion. Need to add parameter for random action

2021-04-03 20:12 UTC, Z-Nouman approved these changes
Looks good! In the future, once we have a solid Q-function, we should add assert statements to verify the agent works as intended.

2021-04-04 15:06 UTC, DonatasTamosauskas requested changes

2021-04-04 15:06 UTC, DonatasTamosauskas commented on dumbbells/Agent.py
> +    def __init__(self, Q, action_space, state_space, reward_space, verbose=False):
Python variables are lowercase (`Q` -> `q`). I saw more non-pythonic variable/functions names. You can look over [pep8](https://www.python.org/dev/peps/pep-0008/) or [google guide](https://google.github.io/styleguide/pyguide.html#316-naming) for python style documentation. I'll point out some, but not all

2021-04-04 15:06 UTC, DonatasTamosauskas commented on dumbbells/Agent.py
> +        self.Q = Q
There should be an online & offline q functions (so initially two copies)

2021-04-04 15:06 UTC, DonatasTamosauskas commented on tests/test_agent.py
> +sys.path.append("../dumbbells")
There's no need to do this, because `dumbbells` is automatically installed during `poetry` initialisation.

2021-04-04 15:06 UTC, DonatasTamosauskas commented on tests/test_agent.py
> +from dumbbells.Agent import Agent
Python modules are lowercase: `from dumbbells.Agent import Agent` -> `from dumbbells.agent import Agent`

2021-04-04 15:06 UTC, DonatasTamosauskas commented on tests/test_agent.py
> +def testQAgent():
Functions are lowecase separated by `_`

2021-04-04 15:06 UTC, DonatasTamosauskas commented on tests/test_agent.py
> +    print("\nStarting testQAgent")
Since we're using `pytest` there's no need to log tests individually, they'll be logged by `pytest` itself

2021-04-04 15:06 UTC, DonatasTamosauskas commented on tests/test_agent.py
> +    # myAgent = Agent.Agent(myQ,action_space,state_space,reward_space,verbose = True)
Unnecessary comment

2021-04-04 15:06 UTC, DonatasTamosauskas commented on tests/test_agent.py
> +if __name__ == "__main__":
`pytest` will execute the tests automatically, no need to execute them manually

2021-04-13 12:20 UTC, DonatasTamosauskas approved these changes

2021-04-13 12:22 UTC, merged